### PR TITLE
added topicstobecovered md file & added ppt 

### PR DESCRIPTION
**Pull request by suprajakosuri01**
I have completed the initial revision of the PowerPoint presentation. However, there are a few more edits to be made. Specifically, I need to incorporate educational videos and quizzes into the presentation.

### CODE REVIEW

**Comment by parthasarathydNU** [comment]
Kindly move the docx file within the project folder:

image

**Comment by suprajakosuri01** [comment]
worked on comments provided

**Comment by suprajakosuri01** [comment]
added final version of PPT for module 1

**Comment by suprajakosuri01** [comment]
transitioned from using PowerPoint to Google Docs for presentation slides. I have included a link in the README.md file that allows you to preview the slides. Additionally, you'll find a link for the project planning related to Module 1.

**Comment by parthasarathydNU** [comment]
> transitioned from using PowerPoint to Google Docs for presentation slides. I have included a link in the README.md file that allows you to preview the slides. Additionally, you'll find a link for the project planning related to Module 1.

It still says that I need access.
image

**Review by parthasarathydNU — APPROVED** [review]
Good job on the first draft of the content. 

Things to work on for the next iteration: 
- Adding chat GPT conversations
- Adding documentation to the github project dashboard

From my side:
- Will share sample submissions for you to review on Monday

**Pull request merged**
